name: Run Tests

on:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Clean Build
        run: dotnet clean

      - name: Build Solution
        run: dotnet build --no-restore --configuration Debug

      - name: Run Tests
        run: dotnet test --no-build --configuration Debug --verbosity detailed